# ReplicaSet

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: repset-articoli
spec:
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
            - artsrv
            - barsrv
  template:
    metadata:
      labels:
        app: artsrv
    spec:
      containers:
      - name: articoli-webservice
        image: nlarocca/articoli-webservice-kube:0.0.1-SNAPSHOT
        ports:
        - containerPort: 5051

#Altri operatori  previsti:
  # In = La label del pod deve avere uno dei volori inseriti in values
  # NotIn = La label del pod NON deve avere uno dei valori inseriti in values
  # Exists = Il key del pod deve avere il nome della key specificato (values non utilizzabile)
  # DoesNotExist = Il key del pod NON deve avere il nome della key specificato (values non utilizzabile)