apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 20Mi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  #hostPath:
  #  path: "/mnt/data"
  gcePersistentDisk:
    pdName: mysqldb
    fsType: ext4